/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package geneticlibraryjava.app;

import geneticlibraryjava.library.GeneticLibrary;


import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        
        GeneticLibrary<int[]> geneticlibrary = new GeneticLibrary<int[]>(int[].class);


    }
}
